### ISSUE TITLE
sign up & sign in tab combine

### ISSUE THREAD

**Issue by JessicaTruskills** [truskills/edx-issues#1]
In itutoring
![image](https://cloud.githubusercontent.com/assets/11550419/6725327/e77ff778-ce2d-11e4-8e08-5357fd4fd8b9.png)

In edx - register now & sign in are different 2 tabs
![image](https://cloud.githubusercontent.com/assets/11550419/6725344/1292fbc2-ce2e-11e4-861b-ebf9466fe63f.png)

Can we do combine 2 tabs in one page like itutoring ?

**Comment by mitulap** [comment]
It is combined in the edx platform. When user clicks on the register now and sign in button edx will show the output as the user experience of edx is designed.
