### ISSUE TITLE
Logo Uploading from edx Studio

### ISSUE THREAD

**Issue by AktaTruskills** [truskills/edx-issues#2]
![image](https://cloud.githubusercontent.com/assets/11550422/6725385/c19affe8-ce2e-11e4-89a9-39814870bb0a.png)

How to Upload logo from edx studio?

**Comment by harshkothari410** [comment]
Give me logo I will update it

**Comment by mitulap** [comment]
Please provide us logo in three size small, medium and large.

**Comment by JessicaTruskills** [comment]
Give me three sizes for logo.

**Comment by JessicaTruskills** [comment]
Waiting for sizes of the logo.

**Comment by mitulap** [comment]
Hey I'll take it from the current website and then will convert it in the desired size.

**Comment by JessicaTruskills** [comment]
![logo](https://cloud.githubusercontent.com/assets/11550419/6775371/36c2d83e-d156-11e4-853a-da119454d99a.jpg)

Use this temporary logo.

**Comment by mitulap** [comment]
Ohhh...all right....I have the one with the current itutoring webstie....
But this one is different and cool so will use this...Thanks for the logo!
