### ISSUE TITLE
Course Editing issue

### ISSUE THREAD

**Issue by AktaTruskills** [truskills/edx-issues#26]
Today we had create one demo course and we are facing the below issues.

First we create one course and Click on Save From Studio. After save if we want to update the course we cant save it and modify it.

**Comment by mitulap** [comment]
You can modify/update your course from the studio itself. Go to the respective course and you will be able to go through the sections that you have added in that course and then click on the particular section and you will be given a page to edit that particular section of the course, also from the same page you can publish that changes directly to reflect in the LMS.

**Comment by AktaTruskills** [comment]
we do the same but cant modify.

_Thanks and Regards_
_Akta Modi_

**Comment by mitulap** [comment]
Login to studio click on the course refer the screen shot

![](https://cloud.githubusercontent.com/assets/6092797/6801158/72ff2186-d24b-11e4-92bc-044316fbe5de.png)

In next screen you have the intro click on that then unit section will come and again click on Unit.
![image](https://cloud.githubusercontent.com/assets/6092797/6801197/c60ed272-d24b-11e4-93a9-6f08c3c61321.png)

Again you have the following screen click on edit to edit particular section

![image](https://cloud.githubusercontent.com/assets/6092797/6801212/e03ceed6-d24b-11e4-8866-382f700a0705.png)

If you click on edit you will have the following screen for text edit.
![image](https://cloud.githubusercontent.com/assets/6092797/6801224/f8946860-d24b-11e4-9be3-ce84f89f4434.png)

**Comment by AktaTruskills** [comment]
I want how to add the Course info? not course ware.

_Thanks and Regards_
_Akta Modi_

**Comment by mitulap** [comment]
You should have mentioned you want to update course info.
Here is the description
- Details of course is added in Course ware, which is added as subsection in course. Course info is all about update. 
  You can go to update in studio for particular course and then add update (In studio in header there is a dropdown which has a optione of updates, you can click on that and edit to edit course info)  which will be visible to LMS after publishing that. Refer this screen shot.

![image](https://cloud.githubusercontent.com/assets/6092797/6801475/0e01150c-d24e-11e4-9297-8abe3c3bd824.png)

  Wiki is something about adding extra details for particular course. You can add that in LMS by enrolling in the course. Go to that course and click on wiki then edit. Now you can add details there.

**Comment by AktaTruskills** [comment]
[image: Inline image 1]
i upload this updates, but alignment is not proper.

_Thanks and Regards_
_Akta Modi_

**Comment by AktaTruskills** [comment]
I want to update Course name, so i re-run the course but after editing i clicked on Save and re-run the course, one error is display and cant update.here is the snapshot.
![image](https://cloud.githubusercontent.com/assets/11550422/6818725/6177d148-d2db-11e4-994a-ed065432cdb3.png)
and after re run i got this error.
![image](https://cloud.githubusercontent.com/assets/11550422/6818733/78810fbc-d2db-11e4-92ba-6cea1ceed30c.png)

**Comment by mitulap** [comment]
You can't change the name there as in that page the students have been given the course code and name of the course so this is internal function. When you check this course in the find course page you will get the name of the course which you have entered, means name will appear without any subject code.
