### ISSUE TITLE
Course image issue

### ISSUE THREAD

**Issue by AktaTruskills** [truskills/edx-issues#27]
If we want to add image with course name how we add? give me specific path.

**Comment by mitulap** [comment]
Go to studio click on the course and go the settings and then click on schedule and details as shown in below screenshot, you will have a page to enter details about course and you can add mail image there as well for the course.
![image](https://cloud.githubusercontent.com/assets/6092797/6801623/8723e51c-d24f-11e4-9a53-080d94c34865.png)

**Comment by mitulap** [comment]
Please close this issue once you get the idea.

**Comment by AktaTruskills** [comment]
I got it.. But You Should have to keep this image uploading Section to the top rather than bottom of the page...

**Comment by mitulap** [comment]
It is a logical flow that edx is following this page is not only about adding course image it has other important information like course schedule and other things so the things are organized accordingly for the page.
