### ISSUE TITLE
MCQ Arrangement Issue

### ISSUE THREAD

**Issue by AktaTruskills** [truskills/edx-issues#28]
We had successfully upload the mcq but from LMS when we can see the MCQ panel in left hand side after section or subsection ?

**Comment by AktaTruskills** [comment]
Please comment on this functionality.

**Comment by mitulap** [comment]
Yes it will come to the section where you have added that MCQ. 
Please refer to this link for exercise related queries. 
http://edx.readthedocs.org/projects/edx-partner-course-staff/en/latest/exercises_tools/index.html
