### ISSUE TITLE
Course Info Issue

### ISSUE THREAD

**Issue by AktaTruskills** [truskills/edx-issues#30]
How can we add the details in Course Info Page? From LMS or From Studio? We cant find any Option?

**Comment by mitulap** [comment]
Here is the description

Details of course is added in Course ware, which is added as subsection in course. Course info is all about update. You can go to update in studio for particular course and then add update (In studio in header there is a dropdown which has a optione of updates, you can click on that and edit to edit course info) which will be visible to LMS after publishing that. Refer this screen shot.
image

![](https://cloud.githubusercontent.com/assets/6092797/6801475/0e01150c-d24e-11e4-9297-8abe3c3bd824.png)

Wiki is something about adding extra details for particular course. You can add that in LMS by enrolling in the course. Go to that course and click on wiki then edit. Now you can add details there.
