### ISSUE TITLE
Wiki must have options

### ISSUE THREAD

**Issue by AktaTruskills** [truskills/edx-issues#31]
We want to Put 4 things in Wiki.
1. Assignment
2. Notes
3. Printed words(GSEB Textbook Page Link)
4. Asthetics(Link of Any topic from Quizlet.com)

At the end We want different 4 panel for that and one panel for Entering all the links and publish in LMS for students.

**Comment by AktaTruskills** [comment]
Please comment on this Functionality, we want to upload pdf files of assignment and notes.
and upload link for reference link.

**Comment by mitulap** [comment]
You can refer this link where they have explained about how to upload assignments, and extra documents for a course. 
http://edx.readthedocs.org/projects/edx-partner-course-staff/en/latest/getting_started/get_started.html
