### ISSUE TITLE
Unenroll issue

### ISSUE THREAD

**Issue by AktaTruskills** [truskills/edx-issues#33]
In LMS, we clicked on Unenroll of Maths GP(guj) course. 
Now how can we enroll this course again ?

**Comment by mitulap** [comment]
same way you have enrolled first time. Go to find course and then click on the course and then register for course. 
P. S. This is a very small and easy question. You could have tried and easily get to know how to enrol for a course. Please give some effort before asking as we have to unnecessarily give more time to such small que. Thanks!

**Comment by AktaTruskills** [comment]
We are not Familiar with Edx and we are tried to learn All Functionalities of Edx... So we have right to ask any easy or Difficult questions to you. Manoj sir told us to ask any questions to you without hesitation.

**Comment by mitulap** [comment]
This is what my point is you are not familiar so spend some more time and you will get the things easily. You don't have to wait for our answer as that will delay your findings and testing. 
You are new to this platform so giving you few links that user manual will help you understand more about edx platform.
http://files.edx.org/edX101_HowToCreateAnEdXCourse.pdf

http://edx.readthedocs.org/projects/edx-partner-course-staff/en/latest/getting_started/index.html

Thanks!
