### ISSUE TITLE
Author image path

### ISSUE THREAD

**Issue by AktaTruskills** [truskills/edx-issues#35]
how can we upload author image ?

![image](https://cloud.githubusercontent.com/assets/11550422/6819585/5c473084-d2e9-11e4-8642-5ed7deabdbd1.png)

See this...

![image](https://cloud.githubusercontent.com/assets/11550422/6819597/b33d7966-d2e9-11e4-9427-eb24bde624d0.png)

**Comment by mitulap** [comment]
For that you have to add one image in course by following this path go to the particular course in studio and then click on content and then click on files & uploads. After clicking files & uploads you will have a page where you can add a file. That added file has a URL and I have used that URL in the screeshot where you have marked the code of img tag for src attribute. You can check the same course and have an idea.
