### ISSUE TITLE
courses tab 

### ISSUE THREAD

**Issue by JessicaTruskills** [truskills/edx-issues#7]
courses tab for all courses

![image](https://cloud.githubusercontent.com/assets/11550419/6748401/0d6f2340-cf0b-11e4-99d0-f800929a0f66.png)

all course appears in front page

![image](https://cloud.githubusercontent.com/assets/11550419/6748411/1fc4b4a6-cf0b-11e4-8839-2bfcf3627f99.png)

**Comment by mitulap** [comment]
This is a user experience part and system will show the number of courses in the front page when user has not logged and surfing as a guest user.

**Comment by mitulap** [comment]
Alternatively user can go to find the courses using find course button in edx
