### ISSUE TITLE
list of the chapters

### ISSUE THREAD

**Issue by JessicaTruskills** [truskills/edx-issues#9]
when we click on any course it will open list of chapters in one page

![image](https://cloud.githubusercontent.com/assets/11550419/6748748/3b3cb2a2-cf0f-11e4-8ae1-e701d76ce661.png)

and here will click on any course than list of chapters open in left side in courseware tab

![image](https://cloud.githubusercontent.com/assets/11550419/6748752/586223b2-cf0f-11e4-95aa-b4c02a72cf35.png)

functionality changed as per edx.

**Comment by mitulap** [comment]
I guess this is not a function change in edx system shows the chapters info in left side. This is how the user experience of the edx has been designed. So I guess function wise this will work as it is working in itutoring. Let me know if you have any doubt.
